name: Upload Website
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Install NPM Dependencies
        run: npm install
      - name: NPM run build
        run: npm run build --if-present
        run: npm test
        env:
          CI: true
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          AWS_S3_BUCKET: ${{ secrets.testbucket11082022 }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AKIAYCPJ7H3EOJ3FPQGE }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
          aws-region: us-east-1
