name: Upload Website
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
        env:
          CI: true
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.testbucket11082022 }}
          AWS_ACCESS_KEY_ID: ${{ AKIAYCPJ7H3EOJ3FPQGE }}
          AWS_SECRET_ACCESS_KEY: ${{ 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 }}
          AWS_REGION: "us-east-1" # optional: defaults to us-east-1
