name: Upload Website
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install NPM Dependencies
        run: npm install dependencies
      - name: NPM run build
        run: npm run build
      - name: NPM Run Tests
        run: npm test
     