name: Upload Website
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: actions/setup-node
      - name: Install NPM Dependencies
        run: npm install

      - name: NPM Run Tests
        run: npm test
     