name: Upload Website
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install NPM Dependencies
        run: npm install
      - name: NPM Run Tests
        run: npm test
      - name: deploy to AWS S3
      - uses: actions/checkout@master
      - uses: jakejarvis/s3-sync-action@master
      env:
        AWS_REGION: us-east-1
        AWS_S3_BUCKET: testbucket11082022
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}