name: Upload Website
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install NPM Dependencies
        run: npm install dependencies
      - name: NPM run build
        run: npm run build
      - name: NPM Run Tests
        run: npm test
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          AWS_S3_BUCKET: testbucket11082022
          AWS_ACCESS_KEY_ID: ${{ secrets.my-access-id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.my-access-key }}
          aws-region: us-east-1
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          AWS_S3_BUCKET: testbucket11082022
          AWS_ACCESS_KEY_ID: ${{ secrets.my-access-id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.my-access-key }}
          aws-region: us-east-1
